<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260423103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add workflow_run and workflow_step_run execution tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE workflow_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workflow_user_id INT NOT NULL, status VARCHAR(20) NOT NULL, trigger_source VARCHAR(50) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_489ACFE2A5224525 ON workflow_run (workflow_user_id)');
        $this->addSql('CREATE INDEX idx_workflow_run_status ON workflow_run (status)');
        $this->addSql('CREATE INDEX idx_workflow_run_started_at ON workflow_run (started_at)');

        $this->addSql('CREATE TABLE workflow_step_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workflow_run_id INT NOT NULL, workflow_step_id INT NOT NULL, workflow_step_user_id INT DEFAULT NULL, step_order SMALLINT NOT NULL, status VARCHAR(20) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, channel_used VARCHAR(50) NOT NULL, template_id_used VARCHAR(36) DEFAULT NULL, error_message TEXT DEFAULT NULL, payload_snapshot JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_538B7C66A8A1A4FD ON workflow_step_run (workflow_run_id)');
        $this->addSql('CREATE INDEX IDX_538B7C6671FE882C ON workflow_step_run (workflow_step_id)');
        $this->addSql('CREATE INDEX IDX_538B7C66567C1454 ON workflow_step_run (workflow_step_user_id)');
        $this->addSql('CREATE INDEX idx_workflow_step_run_status ON workflow_step_run (status)');
        $this->addSql('CREATE INDEX idx_workflow_step_run_scheduled_at ON workflow_step_run (scheduled_at)');

        $this->addSql('ALTER TABLE workflow_run ADD CONSTRAINT FK_489ACFE2A5224525 FOREIGN KEY (workflow_user_id) REFERENCES workflow_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step_run ADD CONSTRAINT FK_538B7C66A8A1A4FD FOREIGN KEY (workflow_run_id) REFERENCES workflow_run (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step_run ADD CONSTRAINT FK_538B7C6671FE882C FOREIGN KEY (workflow_step_id) REFERENCES workflow_step (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step_run ADD CONSTRAINT FK_538B7C66567C1454 FOREIGN KEY (workflow_step_user_id) REFERENCES workflow_step_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE workflow_step_run DROP CONSTRAINT FK_538B7C66A8A1A4FD');
        $this->addSql('ALTER TABLE workflow_step_run DROP CONSTRAINT FK_538B7C6671FE882C');
        $this->addSql('ALTER TABLE workflow_step_run DROP CONSTRAINT FK_538B7C66567C1454');
        $this->addSql('ALTER TABLE workflow_run DROP CONSTRAINT FK_489ACFE2A5224525');

        $this->addSql('DROP TABLE workflow_step_run');
        $this->addSql('DROP TABLE workflow_run');
    }
}
