<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408063812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E6387E3C61F9 ON contact (owner_id)');
        $this->addSql('CREATE TABLE contact_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, contacts_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C377AE77E3C61F9 ON contact_list (owner_id)');
        $this->addSql('CREATE TABLE scheduler_event (id INT NOT NULL, name VARCHAR(255) NOT NULL, day SMALLINT NOT NULL, month SMALLINT NOT NULL, country_code VARCHAR(2) DEFAULT NULL, language VARCHAR(2) NOT NULL, translation_key VARCHAR(255) NOT NULL, name_key VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_country_language ON scheduler_event (country_code, language)');
        $this->addSql('CREATE INDEX idx_month_day ON scheduler_event (month, day)');
        $this->addSql('CREATE TABLE scheduler_event_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, error_message TEXT DEFAULT NULL, cost_calculation DOUBLE PRECISION DEFAULT NULL, executed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, content_snapshot JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scheduler_event_subscription_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43AB550B8A3853B9 ON scheduler_event_history (scheduler_event_subscription_id)');
        $this->addSql('CREATE TABLE scheduler_event_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, template_id VARCHAR(255) DEFAULT NULL, channel VARCHAR(50) NOT NULL, estimated_number_of_contacts INT DEFAULT 0 NOT NULL, cost_per_contact DOUBLE PRECISION DEFAULT 0 NOT NULL, hour SMALLINT DEFAULT NULL, minute SMALLINT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, days_before INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, scheduler_event_id INT NOT NULL, contact_list_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70AC0472A781370A ON scheduler_event_subscription (contact_list_id)');
        $this->addSql('CREATE INDEX idx_user_id ON scheduler_event_subscription (user_id)');
        $this->addSql('CREATE INDEX idx_scheduler_event_id ON scheduler_event_subscription (scheduler_event_id)');
        $this->addSql('CREATE INDEX idx_channel ON scheduler_event_subscription (channel)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE workflow_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status SMALLINT NOT NULL, step_order SMALLINT NOT NULL, channel VARCHAR(50) NOT NULL, delay_unit VARCHAR(20) DEFAULT NULL, delay_value INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, workflow_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_626EE072C7C2CBA ON workflow_step (workflow_id)');
        $this->addSql('CREATE TABLE workflow_step_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, template_id VARCHAR(36) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, is_confirmed_by_user BOOLEAN DEFAULT false NOT NULL, channel VARCHAR(50) NOT NULL, delay_in_minutes INT DEFAULT NULL, sending_time VARCHAR(10) DEFAULT NULL, settings JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, workflow_user_id INT NOT NULL, workflow_step_id INT NOT NULL, excluded_segment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3EACD19DA76ED395 ON workflow_step_user (user_id)');
        $this->addSql('CREATE INDEX IDX_3EACD19DA5224525 ON workflow_step_user (workflow_user_id)');
        $this->addSql('CREATE INDEX IDX_3EACD19D71FE882C ON workflow_step_user (workflow_step_id)');
        $this->addSql('CREATE INDEX IDX_3EACD19DA4ECC77E ON workflow_step_user (excluded_segment_id)');
        $this->addSql('CREATE TABLE workflow_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, original_workflow_id INT NOT NULL, workflow_id INT NOT NULL, segment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C80CC672A76ED395 ON workflow_user (user_id)');
        $this->addSql('CREATE INDEX IDX_C80CC672DB73CC90 ON workflow_user (original_workflow_id)');
        $this->addSql('CREATE INDEX IDX_C80CC6722C7C2CBA ON workflow_user (workflow_id)');
        $this->addSql('CREATE INDEX IDX_C80CC672DB296AAD ON workflow_user (segment_id)');
        $this->addSql('CREATE TABLE workflows (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(100) DEFAULT NULL, workflow_key VARCHAR(100) NOT NULL, workflow_name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6387E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact_list ADD CONSTRAINT FK_6C377AE77E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduler_event_history ADD CONSTRAINT FK_43AB550B8A3853B9 FOREIGN KEY (scheduler_event_subscription_id) REFERENCES scheduler_event_subscription (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduler_event_subscription ADD CONSTRAINT FK_70AC0472A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduler_event_subscription ADD CONSTRAINT FK_70AC04722A925BFB FOREIGN KEY (scheduler_event_id) REFERENCES scheduler_event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduler_event_subscription ADD CONSTRAINT FK_70AC0472A781370A FOREIGN KEY (contact_list_id) REFERENCES contact_list (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step ADD CONSTRAINT FK_626EE072C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step_user ADD CONSTRAINT FK_3EACD19DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step_user ADD CONSTRAINT FK_3EACD19DA5224525 FOREIGN KEY (workflow_user_id) REFERENCES workflow_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step_user ADD CONSTRAINT FK_3EACD19D71FE882C FOREIGN KEY (workflow_step_id) REFERENCES workflow_step (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step_user ADD CONSTRAINT FK_3EACD19DA4ECC77E FOREIGN KEY (excluded_segment_id) REFERENCES contact_list (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_user ADD CONSTRAINT FK_C80CC672A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_user ADD CONSTRAINT FK_C80CC672DB73CC90 FOREIGN KEY (original_workflow_id) REFERENCES workflows (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_user ADD CONSTRAINT FK_C80CC6722C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_user ADD CONSTRAINT FK_C80CC672DB296AAD FOREIGN KEY (segment_id) REFERENCES contact_list (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E6387E3C61F9');
        $this->addSql('ALTER TABLE contact_list DROP CONSTRAINT FK_6C377AE77E3C61F9');
        $this->addSql('ALTER TABLE scheduler_event_history DROP CONSTRAINT FK_43AB550B8A3853B9');
        $this->addSql('ALTER TABLE scheduler_event_subscription DROP CONSTRAINT FK_70AC0472A76ED395');
        $this->addSql('ALTER TABLE scheduler_event_subscription DROP CONSTRAINT FK_70AC04722A925BFB');
        $this->addSql('ALTER TABLE scheduler_event_subscription DROP CONSTRAINT FK_70AC0472A781370A');
        $this->addSql('ALTER TABLE workflow_step DROP CONSTRAINT FK_626EE072C7C2CBA');
        $this->addSql('ALTER TABLE workflow_step_user DROP CONSTRAINT FK_3EACD19DA76ED395');
        $this->addSql('ALTER TABLE workflow_step_user DROP CONSTRAINT FK_3EACD19DA5224525');
        $this->addSql('ALTER TABLE workflow_step_user DROP CONSTRAINT FK_3EACD19D71FE882C');
        $this->addSql('ALTER TABLE workflow_step_user DROP CONSTRAINT FK_3EACD19DA4ECC77E');
        $this->addSql('ALTER TABLE workflow_user DROP CONSTRAINT FK_C80CC672A76ED395');
        $this->addSql('ALTER TABLE workflow_user DROP CONSTRAINT FK_C80CC672DB73CC90');
        $this->addSql('ALTER TABLE workflow_user DROP CONSTRAINT FK_C80CC6722C7C2CBA');
        $this->addSql('ALTER TABLE workflow_user DROP CONSTRAINT FK_C80CC672DB296AAD');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE contact_list');
        $this->addSql('DROP TABLE scheduler_event');
        $this->addSql('DROP TABLE scheduler_event_history');
        $this->addSql('DROP TABLE scheduler_event_subscription');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE workflow_step');
        $this->addSql('DROP TABLE workflow_step_user');
        $this->addSql('DROP TABLE workflow_user');
        $this->addSql('DROP TABLE workflows');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
