<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260504200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Contact email/phone + list membership; marketing_campaign_send audit log.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE contact ADD email VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE contact ADD phone VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE contact ADD contact_list_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_4C62E638A781370A ON contact (contact_list_id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638A781370A FOREIGN KEY (contact_list_id) REFERENCES contact_list (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE marketing_campaign_send (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trigger_source VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, summary JSON DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, marketing_campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_MC_SEND_CAMPAIGN ON marketing_campaign_send (marketing_campaign_id)');
        $this->addSql('ALTER TABLE marketing_campaign_send ADD CONSTRAINT FK_MC_SEND_CAMPAIGN FOREIGN KEY (marketing_campaign_id) REFERENCES marketing_campaign (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE marketing_campaign_send DROP CONSTRAINT FK_MC_SEND_CAMPAIGN');
        $this->addSql('DROP TABLE marketing_campaign_send');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638A781370A');
        $this->addSql('DROP INDEX IDX_4C62E638A781370A');
        $this->addSql('ALTER TABLE contact DROP phone');
        $this->addSql('ALTER TABLE contact DROP email');
        $this->addSql('ALTER TABLE contact DROP contact_list_id');
    }
}
