<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260504120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Content templates and marketing campaigns (Email/SMS campaign management).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE content_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, channel VARCHAR(20) NOT NULL, subject VARCHAR(500) DEFAULT NULL, body TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CONTENT_TEMPLATE_OWNER ON content_template (owner_id)');
        $this->addSql('CREATE TABLE marketing_campaign (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, channel VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, schedule_mode VARCHAR(20) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cron_expression VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, contact_list_id INT DEFAULT NULL, content_template_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_MARKETING_CAMPAIGN_OWNER ON marketing_campaign (owner_id)');
        $this->addSql('CREATE INDEX IDX_MARKETING_CAMPAIGN_LIST ON marketing_campaign (contact_list_id)');
        $this->addSql('CREATE INDEX IDX_MARKETING_CAMPAIGN_TEMPLATE ON marketing_campaign (content_template_id)');
        $this->addSql('ALTER TABLE content_template ADD CONSTRAINT FK_83FF7F557E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE marketing_campaign ADD CONSTRAINT FK_8EC5A30D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE marketing_campaign ADD CONSTRAINT FK_8EC5A30DA781370A FOREIGN KEY (contact_list_id) REFERENCES contact_list (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE marketing_campaign ADD CONSTRAINT FK_8EC5A30D13241D6F FOREIGN KEY (content_template_id) REFERENCES content_template (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE marketing_campaign DROP CONSTRAINT FK_8EC5A30D13241D6F');
        $this->addSql('ALTER TABLE marketing_campaign DROP CONSTRAINT FK_8EC5A30DA781370A');
        $this->addSql('ALTER TABLE marketing_campaign DROP CONSTRAINT FK_8EC5A30D7E3C61F9');
        $this->addSql('ALTER TABLE content_template DROP CONSTRAINT FK_83FF7F557E3C61F9');
        $this->addSql('DROP TABLE marketing_campaign');
        $this->addSql('DROP TABLE content_template');
    }
}
